import { randomBytes } from 'node:crypto';
import { CARD_IDS, MAX_PLAYERS, MIN_PLAYERS_TO_START, STARTING_HAND_SIZE, STARTING_VITALITY, type Player, type PrivatePlayerState, type PublicPlayer, type RoomState } from '../../../packages/shared/src/index.js';
const makeRoomCode=()=>randomBytes(4).toString('hex').toUpperCase(); const makeId=()=>randomBytes(8).toString('hex');
export class Room {
 readonly roomId=makeRoomCode(); readonly hostId:string; phase:RoomState['phase']='lobby'; sceneId:string|null=null; round=0; activePlayerId:string|null=null; winnerId:string|null=null; wishFragments=0; discardPile:string[]=[]; actionLog:string[]=[]; deck:string[]=[]; players=new Map<string,Player>();
 constructor(hostName:string,characterId='yier'){const host:Player={id:makeId(),name:hostName.trim()||'房主',characterId,status:'connected',vitality:STARTING_VITALITY,friendship:0,bonds:[],hand:[]};this.hostId=host.id;this.players.set(host.id,host);this.actionLog.unshift(`${host.name} 创建了房间`)}
 addPlayer(name:string,characterId='bubu'){if(this.phase!=='lobby')throw new Error('游戏已经开始');if(this.players.size>=MAX_PLAYERS)throw new Error('房间已满');const p:Player={id:makeId(),name:name.trim()||'玩家',characterId,status:'connected',vitality:STARTING_VITALITY,friendship:0,bonds:[],hand:[]};this.players.set(p.id,p);this.actionLog.unshift(`${p.name} 加入了房间`);return p}
 removePlayer(id:string){const p=this.players.get(id);if(!p)return;this.players.delete(id);this.actionLog.unshift(`${p.name} 离开了房间`)}
 setReady(id:string){const p=this.players.get(id);if(!p||this.phase!=='lobby')throw new Error('当前无法准备');p.status=p.status==='ready'?'connected':'ready';this.actionLog.unshift(`${p.name}${p.status==='ready'?' 已准备':' 取消准备'}`)}
 start(id:string){if(id!==this.hostId)throw new Error('只有房主可以开始');if(this.phase!=='lobby')throw new Error('游戏已经开始');if(this.players.size<MIN_PLAYERS_TO_START)throw new Error(`至少需要 ${MIN_PLAYERS_TO_START} 名玩家`);this.phase='playing';this.round=1;this.sceneId='dessert-party';this.deck=[...CARD_IDS,...CARD_IDS,...CARD_IDS].sort(()=>Math.random()-.5);for(const p of this.players.values()){p.status='ready';p.hand=this.deck.splice(0,STARTING_HAND_SIZE)}this.activePlayerId=this.players.keys().next().value??null;this.actionLog.unshift('旅程开始！')}
 action(id:string,action:string,cardId?:string,targetId?:string){if(this.phase!=='playing')throw new Error('游戏尚未开始');if(id!==this.activePlayerId)throw new Error('还没轮到你');const p=this.players.get(id);if(!p)throw new Error('玩家不存在');if(cardId){const i=(p.hand??[]).indexOf(cardId);if(i<0)throw new Error('你没有这张牌');p.hand!.splice(i,1);this.discardPile.push(cardId)}if(action==='friendship'&&targetId&&this.players.has(targetId)){p.friendship=Math.min(6,p.friendship+1);const t=this.players.get(targetId)!;t.friendship=Math.min(6,t.friendship+1)}this.actionLog.unshift(`${p.name} ${action==='end-turn'?'结束回合':`使用了 ${cardId??action}`}`);const ids=[...this.players.keys()],next=(ids.indexOf(id)+1)%ids.length;if(next===0)this.round++;this.activePlayerId=ids[next]??null}
 publicState():RoomState{return{roomId:this.roomId,phase:this.phase,hostId:this.hostId,sceneId:this.sceneId,round:this.round,activePlayerId:this.activePlayerId,players:[...this.players.values()].map((p):PublicPlayer=>({id:p.id,name:p.name,characterId:p.characterId,status:p.status,vitality:p.vitality,friendship:p.friendship,bonds:p.bonds,handSize:p.hand?.length??0})),deckSize:this.deck.length,discardPile:this.discardPile.slice(-20),wishFragments:this.wishFragments,actionLog:this.actionLog.slice(0,30),winnerId:this.winnerId}}
 privateState(id:string):PrivatePlayerState{const p=this.players.get(id);if(!p)throw new Error('玩家不存在');return{player:{...p,hand:[...(p.hand??[])]},room:this.publicState()}}
}
export class RoomManager{private rooms=new Map<string,Room>();create(name:string,characterId?:string){const r=new Room(name,characterId);this.rooms.set(r.roomId,r);return r}get(id:string){return this.rooms.get(id.toUpperCase())}join(id:string,name:string,characterId?:string){const r=this.get(id);if(!r)throw new Error('找不到这个房间');return{room:r,player:r.addPlayer(name,characterId)}}removeIfEmpty(id:string){const r=this.get(id);if(r&&r.players.size===0)this.rooms.delete(r.roomId)}}
